apiVersion: v1

kind: Service

metadata:
  name: postgres-service
  labels:
    app: postgres-service
    
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: postgres-pod
